---
title: "Data stats"
author: "Janne Huovari"
date: "21 9 2019"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Labour_cost}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.height = 5.5,
  fig.width = 6.5,
  fig.path = "Fig_stat/"
)

```

```{r setup}
# library(ficomp)

devtools::load_all()

library(dplyr)
library(ggplot2)
library(eurostat)
library(tidyr)
library(ggptt)

set_ptt(14, "sans") 
theme_update(
  legend.text = element_text(size = 14),
  plot.subtitle = element_text(colour = "grey40"),
  plot.caption = element_text(size = 10, face = "plain", colour = "grey40"))


data(naq_eurostat_dat, ulc_oecd_dat, ulc_eurostat_dat)

```

# Eurostat

```{r}

naq_eurostat_dat_raw %>% 
  filter(unit == "CP_MNAC",
         na_item == "B1GQ") %>% 
  drop_na(values) %>% 
  group_by(geo, nace_r2, s_adj) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = nace_r2)) +
    facet_wrap(~ s_adj) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip() +
    geom_hline(yintercept = as.numeric(as.Date("1995-01-01")))

```


```{r}

naq_eurostat_dat_raw %>% 
  filter(nace_r2 == "TOTAL",
         na_item == "EMP_DC") %>% 
  group_by(geo, nace_r2, s_adj) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = unit)) +
    facet_wrap(~ s_adj) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip()

```

# Eurostat ULC

```{r}
 
ulc_eurostat_dat %>% 
  drop_na(values) %>% 
  group_by(geo, na_item) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = na_item)) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip()

```


# OECD

```{r}

ulc_oecd_dat %>% 
  drop_na(values) %>% 
  group_by(geo, na_item) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = na_item)) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip() +
    geom_hline(yintercept = as.numeric(as.Date("1995-01-01")))

```

OECD not in eurostat

```{r}

ulc_oecd_dat %>% 
  filter(!(geo %in% levels(naq_eurostat_dat$geo))) %>% 
  drop_na(values) %>% 
  group_by(geo, na_item) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = na_item)) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip() +
    geom_hline(yintercept = as.numeric(as.Date("1995-01-01")))

```


```{r}

oecd_dat_sna %>% 
  group_by(geo, na_item, unit) %>% 
  mutate(ind_10 = rebase(values, time, 2010)) %>% 
  ungroup() %>% 
  ggplot(aes(time, ind_10, group = geo)) +
  facet_grid(na_item ~ unit, scales = "free_y") +
  geom_line()

```

```{r}

eo_ulc_a_dat %>% 
  drop_na(values) %>% 
  group_by(geo, vars) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = vars)) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip() 

```


```{r}
a_dat_ind %>% 
  filter(nace_r2 == "C") %>% 
  select(geo, time, nulc_aper_va, D1__CP_MNAC, B1G__CLV10_MNAC) %>% 
  gather(vars, values, -geo, -time) %>% 
  drop_na(values) %>% 
  group_by(geo, vars) %>% 
  mutate(tmin = min(time), 
         tmax = max(time)) %>% 
  ungroup() %>% 
  ggplot(aes(geo, ymin = tmin, ymax = tmax, colour = vars)) +
    geom_linerange(position = position_dodge(width = 0.5)) +
    coord_flip() 

```

