---
title: "Labour cost index"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Labour_cost}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(ficomp)

devtools::load_all()

library(dplyr)
library(ggplot2)
library(eurostat)
library(tidyr)
library(ggptt)

set_ptt()

data(naq_eurostat_dat)

base_year <- 2008
base_years <- 2000:2018
geos <- c("FI", "SE", "DE", "FR")
start_time <- "1990-01-01"

```

# data

```{r}

tibble(code = levels(naq_eurostat_dat$na_item), name = label_eurostat(levels(naq_eurostat_dat$na_item), "na_item"))

```


# Nominal unit labour cost

```{r ulc}

lc_dat <- 
  naq_eurostat_dat %>% 
  filter(nace_r2 == "TOTAL") %>% 
  unite(vars, na_item, unit) %>% 
  # filter(vars %in% c("D1_CP_MNAC", "B1G_CLV10_MNAC")) %>% 
  spread(vars, values) %>% 
  group_by(geo) %>% 
  mutate(
    # nominal unit labour cost
    ulc = ind_ulc(D1_CP_MNAC, B1G_CLV10_MNAC, time = time, baseyear = base_year),
    # nominal unit labour cost, adjusted to take account emploees/emplyed share
    ulc_adj = ind_ulc(D1_CP_MNAC / SAL_DC_THS_HW, B1G_CLV10_MNAC / EMP_DC_THS_HW, time = time, baseyear = base_year)) %>% 
  ungroup()

lc_dat %>% 
  filter(geo %in% geos,
         time >= start_time) %>% 
  select(geo, time, ulc, ulc_adj) %>% 
  gather(ind, values, -geo, -time) %>% 
  ggplot(aes(time, values, colour = geo)) +
  geom_line() +
  facet_wrap(~ ind)

```

# Nominal unit labour cost manufacturing

```{r ulc_c}

lc_dat_c <- 
  naq_eurostat_dat %>% 
  filter(nace_r2 == "C") %>% 
  unite(vars, na_item, unit) %>% 
  # filter(vars %in% c("D1_CP_MNAC", "B1G_CLV10_MNAC")) %>% 
  spread(vars, values) %>% 
  group_by(geo) %>% 
  mutate(
    # nominal unit labour cost
    ulc = ind_ulc(D1_CP_MNAC, B1G_CLV10_MNAC, time = time, baseyear = base_years),
    # nominal unit labour cost, adjusted to take account emploees/emplyed share
    ulc_adj = ind_ulc(D1_CP_MNAC / SAL_DC_THS_HW, B1G_CLV10_MNAC / EMP_DC_THS_HW, time = time, baseyear = base_years)) %>% 
  ungroup()

lc_dat_c %>% 
  filter(geo %in% geos,
         time >= start_time) %>% 
  select(geo, time, ulc, ulc_adj) %>% 
  gather(ind, values, -geo, -time) %>% 
  ggplot(aes(time, values, colour = geo)) +
  geom_line() +
  facet_wrap(~ ind)

```

# Hourly compensation

```{r comp_h}


naq_eurostat_dat %>% 
  filter(nace_r2 %in% c("TOTAL", "C")) %>% 
  unite(vars, na_item, unit) %>% 
  # filter(vars %in% c("D1_CP_MNAC", "B1G_CLV10_MNAC")) %>% 
  spread(vars, values) %>% 
  group_by(geo, nace_r2) %>% 
  mutate(comp_h = rebase(D1_CP_MNAC / SAL_DC_THS_HW, time = time, baseyear = base_year),
         d_comp_h = 100 * (comp_h / lag(comp_h, 4) - 1)) %>% 
  ungroup() %>% 
  filter(geo %in% geos,
         time >= start_time) %>% 
  ggplot(aes(time, d_comp_h, colour = geo)) +
  geom_line() +
  facet_wrap(~ nace_r2)

```
```{r d_comp_h}


naq_eurostat_dat %>% 
  filter(nace_r2 %in% c("TOTAL", "C")) %>% 
  unite(vars, na_item, unit) %>% 
  # filter(vars %in% c("D1_CP_MNAC", "B1G_CLV10_MNAC")) %>% 
  spread(vars, values) %>% 
  group_by(geo, nace_r2) %>% 
  mutate(comp_h = rebase(D1_CP_MNAC / SAL_DC_THS_HW, time = time, baseyear = base_year),
         d_comp_h = 100 * (comp_h / lag(comp_h, 4) - 1)) %>% 
  ungroup() %>% 
  filter(geo %in% c("FI", "SE"),
         time >= "2010-01-01") %>% 
  ggplot(aes(time, d_comp_h, colour = geo)) +
  geom_line() +
  facet_wrap(~ nace_r2)

```

# Relative nominal unit labour cost

```{r rel_ulc}

ea_weights <- weights_bis_broad %>% 
  filter(time == max(time),
         geo_base == "FI",
         geo != geo_base,
         geo %in% eurostat::ea_countries$code) %>% 
  select(geo, weight) %>% 
  mutate(weight = weight / sum(weight))

lc_dat %>% 
  filter(time >= "1995-01-01") %>% 
  left_join(ea_weights, by = "geo") %>% 
  group_by(time, nace_r2) %>% 
  # summarise(tt = length(geo))
  summarise(rel_ulc = 100 * ulc[geo == "FI"] / sum(ulc * weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
    ggplot(aes(time, rel_ulc, colour = nace_r2)) +
  geom_line()
  

```

